version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "RashadAnsari"
    labels:
      - "actions"
      - "dependencies"
