{{- define "helmet.app" -}}
{{- if .Values.configMap.data }}
{{ include "helmet.configmap" . }}
{{- end }}

{{- if .Values.image.repository }}
{{- if include "helmet.isStatefulSet" . }}
{{ include "helmet.statefulset" . }}
{{- else }}
{{ include "helmet.deployment" . }}
{{- end }}
{{- end }}

{{ include "helmet.service.headless" . }}

{{ include "helmet.persistence" . }}

{{ include "helmet.hpa" . }}
{{ include "helmet.ingress" . }}

{{- if or .Values.secret.data .Values.secret.stringData }}
{{ include "helmet.secret" . }}
{{- end }}

{{ include "helmet.tls.secrets" . }}
{{ include "helmet.tls.selfsigned" . }}

{{- if and .Values.ports .Values.service.ports }}
{{ include "helmet.service" . }}
{{- end }}

{{ include "helmet.serviceaccount" . }}
{{ include "helmet.servicemonitor" . }}
{{ include "helmet.cronjob" . }}
{{ include "helmet.podmonitor" . }}
{{- end }}
