apiVersion: v2
name: simple
description: Simple Helm application chart sample
type: application
version: "0.1.0"
appVersion: "0.1.0"

maintainers:
  - name: Rashad Ansari
    url: https://github.com/RashadAnsari

dependencies:
  - name: helmet
    version: ^0
    repository: oci://ghcr.io/rashadansari/charts
    import-values:
      - defaults
